name: system_monitor_cli
description: A CLI tool to start and stop the System Monitor server.
version: 1.0.3
homepage: https://github.com/14h4i/system_monitor_cli
repository: https://github.com/14h4i/system_monitor_cli.git

executables:
  system_monitor_cli: system_monitor_cli

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  process_run: ^0.13.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: SystemMonitorCliLinux
      windows:
        pluginClass: SystemMonitorCliWindows
      macos:
        pluginClass: SystemMonitorCliMacos
