name: system_monitor_cli
description: A CLI tool to start and stop the System Monitor server.
version: 1.0.0
homepage: https://github.com/14h4i/system_monitor_cli
repository: https://github.com/14h4i/system_monitor_cli.git
environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  args: ^2.4.1
  flutter:
    sdk: flutter
  process_run: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
